[package]
name = "laika"
version = "0.1.0"
edition = "2024"

[dependencies]
laika_combiner = { path = "../laika_combiner"}
clap = { version = "4.5.32", features = ["derive"] }
tokio = "1.44.1"
serde_yaml = "0.9.34+deprecated"
